# Numpy- inclass assignment 
## Submit your work using GitHub to Moodle

### Generate a random numpy array for Month of October where the highest temperature varies between 48-81 degree Farenheit
- Keep in mind the length of the month
- set a random seed of 1 for regenerate
- Display the numpy array named `Temp_O` and find out the minimum and maximum temperature of month

In [1]:
import numpy as np
np.random.seed(1)
Temp_0=np.random.randint(48,81,31)

In [2]:
Temp_0

array([60, 56, 57, 59, 53, 63, 48, 64, 49, 60, 55, 54, 73, 68, 66, 68, 59,
       76, 77, 62, 52, 71, 71, 78, 80, 70, 61, 57, 55, 70, 49])

In [3]:
Temp_D=np.load('Temp_December.npy')

### Load the numpy file `Temp_December` and store it to a variable named Temp_D

In [4]:
Temp_D=np.load('Temp_December.npy')

In [5]:
Temp_D

array([44, 50, 19, 15, 16, 18, 12, 22,  7, 23,  8, 19, 14, 52, 13, 32, 57,
       27, 44, 25, 27, 18, 49, 35, 36, 21, 57, 11, 30, 30, 48])

### Compare two numpy array - Temp_O and Temp_D
- Elementwise
- Arraywise

In [6]:
Temp_0<Temp_D # october temperature is more than december temp for each day

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [7]:
Temp_D==Temp_0 # none are equal

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [8]:
#array wise
np.array_equal(Temp_0,Temp_0)

True

### Find out the:
- Average temperature
- Standard deviation
- Varience
- Minimum temp
- Maximum temp
- Median
#### for Month of December

In [9]:
print('average temperature:', round(Temp_D.mean()))

average temperature: 28


In [10]:
print('standard deviation:', round(Temp_D.std()))

standard deviation: 15


In [11]:
print('minimum:', round(Temp_D.min()))

minimum: 7


In [14]:
print('maximum:', Temp_D.max())

maximum: 57


In [17]:
print('median:', np.median(Temp_D))

median: 25.0


In [16]:
print('variance:', Temp_D.var())

variance: 220.3579604578564


### Plot the distribution of December Temperature using Matplotlib
- add title and create proper labels

In [ ]:
import matplotlib.pyplot as pit
pit.hist(Temp_D)
plt.title('Temperature distribution of december')
plt.xlabel('Temp(F)')
plt.ylabel('Frequency')
plt.show

### Convert the Temp_D to Celsius and store it to a variable names Temp_C. 
- Round off the result
- Save it to a numpy file called DecemberTemp_Celsius

In [ ]:
Temp_D

In [ ]:
Temp_C=np.round((Temp_0-32)*(5/9))

In [ ]:
Temp_C

In [ ]:
np.save('DecemberTemp_Celsius.npy',Temp_C)

In [ ]:
y=np.load('DecemberTemp_Celsius.npy')